os: linux
sudo: false
language: python
python:
    - "3.7"
virtualenv:
  system_site_packages: true
before_install:
  - cp -rp ~/kubeasy/tests/.kube ~
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest